name: Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.35.1'

      - run: flutter pub get
      - run: flutter build apk --release -v

      - name: List outputs
        if: always()
        run: |
          ls -la build/app/outputs/flutter-apk || true
          ls -la android/app/build/outputs/apk || true

      - name: Upload APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mas-release-apk
          path: build/app/outputs/flutter-apk/*.apk
          if-no-files-found: warn
