name: Build Flutter APK (Release)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          sdkmanager --install \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: Setup Flutter (stable 3.35.1)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'
          channel: 'stable'
          cache: true

      - name: Flutter doctor (for logs)
        run: flutter doctor -v

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK (release, split per ABI)
        run: flutter build apk --release --split-per-abi -v

      - name: List outputs
        if: always()
        run: |
          echo "== flutter-apk =="
          ls -R build/app/outputs/flutter-apk || true
          echo "== gradle apk =="
          ls -R android/app/build/outputs/apk || true

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: mas-apk
          path: |
            build/app/outputs/flutter-apk/*.apk
            android/app/build/outputs/apk/**/*.apk
