name: Build Flutter APK (Release)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.1"
          channel: "stable"
          cache: true

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build APK (release, split per ABI)
        run: flutter build apk --release --split-per-abi -v

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: MAS-APK
          path: android/app/build/outputs/flutter-apk/*.apk
          if-no-files-found: warn
