name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build release APK (split per ABI)
        run: flutter build apk --release --split-per-abi

      - name: List APK outputs
        run: |
          echo "=== build/app/outputs/flutter-apk ==="
          ls -lah build/app/outputs/flutter-apk || true
          echo "=== android/app/build/outputs/apk ==="
          ls -lah android/app/build/outputs/apk || true

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: |
            build/app/outputs/flutter-apk/*.apk
            android/app/build/outputs/apk/**/*.apk
          if-no-files-found: warn
