name: Build Flutter APK (Release)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter (stable 3.35.1)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.35.1"

      - name: Flutter doctor (quick)
        run: flutter doctor -v || true

      - name: Pub get
        run: flutter pub get

      - name: Build APK (release, split per ABI)
        run: flutter build apk --release --split-per-abi -v

      - name: List outputs
        if: always()
        run: |
          echo "== flutter-apk =="
          ls -la build/app/outputs/flutter-apk || true
          echo "== gradle apks =="
          ls -la android/app/build/outputs/apk || true

      - name: Upload APKs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mas-ai-apks
          path: |
            build/app/outputs/flutter-apk/*.apk
            android/app/build/outputs/apk/**/*.apk
          if-no-files-found: warn
